<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Projects – Illia Kovalenko</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-7cf6dd9b30dd1244900d342ab7296f0b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-e03fe961f342b3c7a8289c94da64632f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-7cf6dd9b30dd1244900d342ab7296f0b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script defer="" src="../js/lang-switch.js"></script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/ik-monogram.svg" alt="" class="navbar-logo light-content">
    <img src="../images/ik-monogram.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Illia Kovalenko</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../en/index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../en/projects.html" aria-current="page"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../en/method.html"> 
<span class="menu-text">Approach</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../en/cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../en/contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../fr/"> 
<span class="menu-text">Français</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-ai-impact" id="toc-sec-ai-impact" class="nav-link active" data-scroll-target="#sec-ai-impact">1. AI Impact in Student Life</a>
  <ul class="collapse">
  <li><a href="#project-resources" id="toc-project-resources" class="nav-link" data-scroll-target="#project-resources">Project resources</a></li>
  <li><a href="#sec-project-overview" id="toc-sec-project-overview" class="nav-link" data-scroll-target="#sec-project-overview">Project overview</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#sec-analytical-questions" id="toc-sec-analytical-questions" class="nav-link" data-scroll-target="#sec-analytical-questions">Analytical questions and main variables</a></li>
  <li><a href="#sec-data-preparation" id="toc-sec-data-preparation" class="nav-link" data-scroll-target="#sec-data-preparation">Data loading and preparation (character variables -&gt; factors)</a></li>
  <li><a href="#gpa-change" id="toc-gpa-change" class="nav-link" data-scroll-target="#gpa-change">GPA change</a></li>
  <li><a href="#sec-career-confidence" id="toc-sec-career-confidence" class="nav-link" data-scroll-target="#sec-career-confidence">Career confidence</a></li>
  <li><a href="#sec-ai-usage" id="toc-sec-ai-usage" class="nav-link" data-scroll-target="#sec-ai-usage">AI usage and adoption</a></li>
  <li><a href="#sec-ethics" id="toc-sec-ethics" class="nav-link" data-scroll-target="#sec-ethics">Ethical concerns</a></li>
  <li><a href="#sec-time-saved" id="toc-sec-time-saved" class="nav-link" data-scroll-target="#sec-time-saved">Time saved</a></li>
  <li><a href="#sec-clustering" id="toc-sec-clustering" class="nav-link" data-scroll-target="#sec-clustering">Clustering</a></li>
  </ul></li>
  <li><a href="#sec-main-results" id="toc-sec-main-results" class="nav-link" data-scroll-target="#sec-main-results">Main results</a></li>
  <li><a href="#sec-interpretation" id="toc-sec-interpretation" class="nav-link" data-scroll-target="#sec-interpretation">Interpretation</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations">Limitations</a></li>
  </ul></li>
  <li><a href="#python-data-analysis-project" id="toc-python-data-analysis-project" class="nav-link" data-scroll-target="#python-data-analysis-project">2. Python data analysis project</a></li>
  <li><a href="#sql-and-database-project" id="toc-sql-and-database-project" class="nav-link" data-scroll-target="#sql-and-database-project">3. SQL and database project</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Projects</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This page presents a selection of data analysis projects developed to demonstrate applied analytical skills, statistical reasoning, data structuring, and communication.</p>
<p>The portfolio is structured around three complementary tracks:</p>
<ol type="1">
<li><strong>R / Statistical analysis</strong><br>
</li>
<li><strong>Python / Data analysis</strong><br>
</li>
<li><strong>SQL / Databases and data modeling</strong></li>
</ol>
<p>The first project below focuses on exploratory impact analysis using R.</p>
<hr>
<section id="sec-ai-impact" class="level1">
<h1>1. AI Impact in Student Life</h1>
<section id="project-resources" class="level2">
<h2 class="anchored" data-anchor-id="project-resources">Project resources</h2>
<ul>
<li><a href="https://www.kaggle.com/datasets/sohaibdevv/ai-and-student-life-2026-the-new-normal">Original Kaggle dataset used for this project</a></li>
<li><a href="..\en/ai_analysis.R">Download the R script</a></li>
<li><a href="..\en/database.csv">Download the dataset</a></li>
</ul>
</section>
<section id="sec-project-overview" class="level2">
<h2 class="anchored" data-anchor-id="sec-project-overview">Project overview</h2>
<p>This project explores a dataset on AI usage and student life. The objective is to assess whether AI usage is associated with academic performance, career confidence, ethical concerns, and perceived productivity gains.</p>
<p>The analysis was conducted in <strong>R</strong>, using mainly the <code>tidyverse</code>, base statistical functions, and a limited number of additional libraries for modeling and result formatting (like <code>MASS</code> for ordered / multinomial models, <code>broom</code> for tidy regression models, and <code>stats</code> for clustering).</p>
<p>The project is exploratory. Since the dataset does not include a control group – a distinct group of students not using AI – the results cannot unwind causal relationships. The objective is not to prove that AI improves student outcomes, but to evaluate whether the available data supports meaningful statistical relationships.</p>
<hr>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="sec-analytical-questions" class="level3">
<h3 class="anchored" data-anchor-id="sec-analytical-questions">Analytical questions and main variables</h3>
<p>The analysis focuses on five main questions:</p>
<ol type="1">
<li>Is there a measurable change in GPA after AI usage?</li>
<li>Do AI usage variables explain GPA change?</li>
<li>Is career confidence associated with GPA or AI usage?</li>
<li>Are ethical concerns structured by AI usage behavior?</li>
<li>Can students be segmented into meaningful AI usage profiles?</li>
</ol>
<p>GPA scores, career confidence, and perceived ethical concerns were selected as the main dependent variables. These indicators are commonly used in educational and training-related research, and provide a standardized framework for assessing potential outcomes associated with AI usage.</p>
<p>The dataset includes only two socio-demographic variables, <code>Age</code> and <code>Major</code>. This limited set of control variables restricts the ability to account for structural heterogeneity across students (e.g., socio-economic background, prior academic trajectory, institutional context), and therefore constrains the depth of any impact analysis.</p>
<p>In addition, the AI usage variables (task frequency, main usage case, primary tool, and time saved) are self-reported measures collected through a questionnaire. As such, they reflect subjective perceptions rather than observed behavior, which introduces potential biases (recall bias, social desirability bias, and approximation effects).</p>
<p>Finally, descriptive statistics indicate a high level of uniformity in distributions across the 1,500 observations. Combined with the discretized structure of several variables (notably GPA), this raises questions regarding the empirical richness of the dataset. The data may be simplified, simulated, or heavily standardized, which limits variability and reduces the likelihood of identifying strong statistical relationships.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Methodological positioning">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Methodological positioning
</div>
</div>
<div class="callout-body-container callout-body">
<p>As a result, the analysis should be interpreted as an exploratory exercise focused on methodological rigor rather than as evidence of real-world relationships.</p>
</div>
</div>
<hr>
</section>
<section id="sec-data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="sec-data-preparation">Data loading and preparation (character variables -&gt; factors)</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>tbl_database <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"database.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1500 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): Student_ID, Major, Primary_AI_Tool, Main_Usage_Case, AI_Ethics_Concern
dbl (6): Age, Task_Frequency_Daily, GPA_Baseline, GPA_Post_AI, Time_Saved_Ho...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tbl_database)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,500
Columns: 11
$ Student_ID              &lt;chr&gt; "STU-6019", "STU-6962", "STU-2338", "STU-1380"…
$ Age                     &lt;dbl&gt; 23, 22, 18, 19, 19, 19, 19, 20, 20, 19, 20, 24…
$ Major                   &lt;chr&gt; "Software Engineering", "Modern History", "Dat…
$ Primary_AI_Tool         &lt;chr&gt; "Gemini Pro", "GitHub Copilot", "Perplexity", …
$ Task_Frequency_Daily    &lt;dbl&gt; 1, 3, 2, 5, 10, 4, 1, 3, 1, 5, 2, 4, 1, 5, 4, …
$ Main_Usage_Case         &lt;chr&gt; "Code Debugging", "Essay Drafting", "Literatur…
$ GPA_Baseline            &lt;dbl&gt; 2.62, 3.99, 2.57, 2.67, 3.65, 3.21, 3.87, 3.18…
$ GPA_Post_AI             &lt;dbl&gt; 2.62, 4.00, 2.57, 2.87, 3.85, 3.41, 3.97, 3.08…
$ Time_Saved_Hours_Weekly &lt;dbl&gt; 9, 7, 15, 12, 5, 8, 7, 2, 13, 10, 8, 6, 6, 14,…
$ AI_Ethics_Concern       &lt;chr&gt; "Medium", "Medium", "High", "Low", "High", "Me…
$ Career_Confidence_Score &lt;dbl&gt; 3, 4, 7, 5, 9, 4, 1, 9, 8, 3, 4, 10, 4, 3, 5, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">is.na</span>(tbl_database))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tbl_database <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.character) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">contains</span>(<span class="st">"ID"</span>), as.factor),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">gpa_diff =</span> GPA_Post_AI <span class="sc">-</span> GPA_Baseline</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tbl_database)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Student_ID        Age                            Major    
 Length   :1500   Min.   :18.00   Biology                :259  
 N.unique :1500   1st Qu.:20.00   Business Administration:256  
 N.blank  :   0   Median :21.00   Data Science           :259  
 Min.nchar:   8   Mean   :21.49   Fine Arts              :263  
 Max.nchar:   8   3rd Qu.:23.00   Modern History         :221  
                  Max.   :25.00   Software Engineering   :242  
       Primary_AI_Tool Task_Frequency_Daily          Main_Usage_Case
 ChatGPT-4o    :288    Min.   : 1.000       Brainstorming    :286   
 Claude 3.5    :297    1st Qu.: 3.000       Code Debugging   :264   
 Gemini Pro    :302    Median : 5.000       Essay Drafting   :301   
 GitHub Copilot:311    Mean   : 5.407       Exam Prep        :341   
 Perplexity    :302    3rd Qu.: 8.000       Literature Review:308   
                       Max.   :10.000                               
  GPA_Baseline    GPA_Post_AI    Time_Saved_Hours_Weekly AI_Ethics_Concern
 Min.   :2.500   Min.   :2.400   Min.   : 2.00           High  :496       
 1st Qu.:2.880   1st Qu.:2.980   1st Qu.: 5.00           Low   :523       
 Median :3.260   Median :3.360   Median : 9.00           Medium:481       
 Mean   :3.257   Mean   :3.345   Mean   : 8.51                            
 3rd Qu.:3.620   3rd Qu.:3.710   3rd Qu.:12.00                            
 Max.   :4.000   Max.   :4.000   Max.   :15.00                            
 Career_Confidence_Score    gpa_diff       
 Min.   : 1.000          Min.   :-0.10000  
 1st Qu.: 3.000          1st Qu.: 0.00000  
 Median : 5.000          Median : 0.10000  
 Mean   : 5.417          Mean   : 0.08773  
 3rd Qu.: 8.000          3rd Qu.: 0.20000  
 Max.   :10.000          Max.   : 0.30000  </code></pre>
</div>
</div>
<p>The dataset contains 1,500 observations and no missing values. Character variables were converted into factors, and a new variable, <code>gpa_diff</code>, was created to measure the difference between post-AI GPA and baseline GPA.</p>
<hr>
</section>
<section id="gpa-change" class="level3">
<h3 class="anchored" data-anchor-id="gpa-change">GPA change</h3>
<section id="sec-gpa-descriptive" class="level4">
<h4 class="anchored" data-anchor-id="sec-gpa-descriptive">Descriptive analysis</h4>
<p>The first step is descriptive. The summaries provided contain all the basic descriptive statistics. However, before modeling any relationship, I examine whether the dataset contains an observable GPA difference after AI usage.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>gpa_summary <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(gpa_diff),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(gpa_diff),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(gpa_diff),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(gpa_diff),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(gpa_diff)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>gpa_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
     min median   mean    sd   max
   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 -0.100  0.100 0.0877 0.135 0.300</code></pre>
</div>
</div>
<p>The average GPA difference is positive, with a mean increase of approximately +0.088 GPA points.</p>
<p>In a different way, these descriptive statistics can be read and compared quickly via a boxplot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plot_gpa_diff <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> gpa_diff)) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#4C78A8"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.08</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Statistical distribution of GPA scores' difference"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"GPA difference"</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>plot_gpa_diff</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Grouped summaries show small differences in GPA scores across majors, tools, and usage cases.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>gpa_by_major <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(gpa_diff),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(gpa_diff),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(gpa_diff),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(gpa_diff),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(gpa_diff),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> Major</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>gpa_by_tool <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(gpa_diff),</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(gpa_diff),</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(gpa_diff),</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(gpa_diff),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> Primary_AI_Tool</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>gpa_by_usage <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(gpa_diff),</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(gpa_diff),</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(gpa_diff),</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(gpa_diff),</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> Main_Usage_Case</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>gpa_by_major</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  Major                      min median   mean    sd   max
  &lt;fct&gt;                    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Software Engineering    -0.100 0.100  0.102  0.138 0.300
2 Biology                 -0.100 0.100  0.0932 0.140 0.300
3 Business Administration -0.100 0.100  0.0909 0.134 0.300
4 Data Science            -0.100 0.100  0.0839 0.128 0.300
5 Modern History          -0.100 0.100  0.0810 0.133 0.300
6 Fine Arts               -0.100 0.0700 0.0751 0.135 0.300</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>gpa_by_tool</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  Primary_AI_Tool    min median   mean   max
  &lt;fct&gt;            &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 ChatGPT-4o      -0.100 0.100  0.0941 0.300
2 Perplexity      -0.100 0.100  0.0920 0.300
3 GitHub Copilot  -0.100 0.100  0.0908 0.300
4 Gemini Pro      -0.100 0.100  0.0817 0.300
5 Claude 3.5      -0.100 0.1000 0.0802 0.300</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>gpa_by_usage</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  Main_Usage_Case      min median   mean   max
  &lt;fct&gt;              &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 Code Debugging    -0.100  0.100 0.0948 0.300
2 Essay Drafting    -0.100  0.100 0.0877 0.300
3 Brainstorming     -0.100  0.100 0.0876 0.300
4 Literature Review -0.100  0.100 0.0867 0.300
5 Exam Prep         -0.100  0.100 0.0834 0.300</code></pre>
</div>
</div>
<p>At this stage, the descriptive statistics suggest a small positive GPA shift, but they do not stipulate that this change is statistically significant and do not explain what drives this change.</p>
<p>Another way to visualise the GPA difference, is to construct a scatter plot, where all the points above the line <code>y = x</code> represent students’ improvement.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>plot_gpa_scatter <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> GPA_Baseline, <span class="at">y =</span> GPA_Post_AI)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.02</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">height =</span> <span class="fl">0.2</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.9</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">0.01</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"#4C78A8"</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"GPA Before vs After AI Usage"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Points above the line indicate improvement"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Baseline GPA"</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Post-AI GPA"</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"italic"</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>plot_gpa_scatter</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="sec-gpa-distribution" class="level4">
<h4 class="anchored" data-anchor-id="sec-gpa-distribution">GPA difference distribution</h4>
<p>Before using statistical tests, the distribution of the paired differences must be inspected. For a paired t-test, the normality assumption applies to the difference, not to the two GPA variables separately.</p>
<p>The most basic way to proceed with our assumption verification, is to construct a normal Q-Q plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(tbl_database<span class="sc">$</span>gpa_diff)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(tbl_database<span class="sc">$</span>gpa_diff, <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For a better visual representation, we shall construct a histogram of the <code>gpa_diff</code> as well.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>plot_gpa_hist <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gpa_diff)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#4C78A8"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of GPA Difference"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"GPA_Post_AI - GPA_Baseline"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Count"</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>plot_gpa_hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution is discretized, most likely due to rounding effects in GPA values: a GPA score in the present dataset is systematically rounded up.</p>
<p>This limits strict normality, but the sample size (=1500) is large enough for the <strong>paired t-test</strong> to remain robust. A non-parametric <strong>Wilcoxon signed-rank test</strong> is also used as a robustness check in <a href="#sec-gpa-tests" class="quarto-xref">Section&nbsp;1.3.3.3</a>.</p>
<hr>
</section>
<section id="sec-gpa-tests" class="level4">
<h4 class="anchored" data-anchor-id="sec-gpa-tests">GPA statistical testing</h4>
<p>The first inferential question is deliberately simple: <strong>do students report a higher GPA after AI usage than before?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Statistical test: paired t-test">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Statistical test: paired t-test
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question: </strong> Is post-AI GPA significantly different from baseline GPA?</p>
<p><strong>Null hypothesis (H0):</strong> There is no mean difference between baseline GPA and post-AI GPA.</p>
<p><strong>Alternative hypothesis (H1):</strong> There is a mean difference between baseline GPA and post-AI GPA.</p>
<p><strong>Method:</strong> A paired t-test is used because both GPA measures are observed for the same students.</p>
<p><strong>Assumptions:</strong> The key normality assumption applies to the paired differences. As shown in <a href="#sec-gpa-distribution" class="quarto-xref">Section&nbsp;1.3.3.2</a>, the difference is discretized and not perfectly normal. However, given the large sample size, the paired t-test should remain robust.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  tbl_database<span class="sc">$</span>GPA_Post_AI,tbl_database<span class="sc">$</span>GPA_Baseline,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(t_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  estimate statistic   p.value parameter conf.low conf.high method   alternative
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;      
1   0.0877      25.2 3.75e-117      1499   0.0809    0.0946 Paired … two.sided  </code></pre>
</div>
</div>
<p>The paired t-test is complemented with a non-parametric test because the GPA difference distribution is discretized.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Robustness check: Wilcoxon signed-rank test">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Robustness check: Wilcoxon signed-rank test
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Null hypothesis (H0):</strong> The median paired difference is equal to zero.</p>
<p><strong>Alternative hypothesis (H1):</strong> The median paired difference is not equal to zero.</p>
<p><strong>Method:</strong> The Wilcoxon signed-rank test ranks the absolute paired differences and checks whether positive and negative ranks are balanced.</p>
<p><strong>Reason for use:</strong> This test is less sensitive to deviations from normality and is appropriate as a robustness check after the diagnostic findings in <a href="#sec-gpa-distribution" class="quarto-xref">Section&nbsp;1.3.3.2</a>.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>wilcox_test <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  tbl_database<span class="sc">$</span>GPA_Post_AI,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  tbl_database<span class="sc">$</span>GPA_Baseline,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(wilcox_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic p.value method                                           alternative
      &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                                            &lt;chr&gt;      
1    608061       0 Wilcoxon signed rank test with continuity corre… two.sided  </code></pre>
</div>
</div>
<p>Both tests indicate a statistically significant (<code>p ≈ 0</code>) GPA increase after AI usage. Positive differences dominate negative ones across observations. In other terms, students tend to improve more often than they decline. However, the magnitude of the average change remains modest.</p>
<p>Our next step is to test whether AI usage variables actually explain this change.</p>
<hr>
</section>
<section id="sec-gpa-models" class="level4">
<h4 class="anchored" data-anchor-id="sec-gpa-models">Modeling GPA outcomes</h4>
<p>The statistical tests show that GPA increases on average. The modeling stage asks a different question: <strong>can AI usage variables explain variation in GPA outcomes?</strong></p>
<hr>
<section id="naive-model-gpa-difference-explained-by-ai-usage" class="level5">
<h5 class="anchored" data-anchor-id="naive-model-gpa-difference-explained-by-ai-usage">Naive model: GPA difference explained by AI usage</h5>
<div class="callout callout-style-default callout-tip callout-titled" title="Model 1: OLS model on GPA difference">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Model 1: OLS model on GPA difference
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Do AI usage variables explain GPA change?</p>
<p><strong>Dependent variable:</strong> <code>gpa_diff = GPA_Post_AI - GPA_Baseline</code></p>
<p><strong>Null hypothesis (H0):</strong> AI usage variables have no association with GPA change.</p>
<p><strong>Alternative hypothesis (H1):</strong> At least one AI usage variable is associated with GPA change.</p>
<p><strong>Method:</strong> OLS regression is used as a first explanatory model.</p>
<p><strong>Assumptions and diagnostics:</strong> Residual diagnostics are inspected after model estimation. As discussed in <a href="#sec-gpa-distribution" class="quarto-xref">Section&nbsp;1.3.3.2</a>, the dependent variable is discretized, so the model is treated as exploratory rather than definitive in terms of impact analysis.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>model_gpa_diff <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  gpa_diff <span class="sc">~</span> Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_gpa_diff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gpa_diff ~ Primary_AI_Tool + Task_Frequency_Daily + 
    Main_Usage_Case + Time_Saved_Hours_Weekly, data = tbl_database)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.207516 -0.093928  0.007269  0.110375  0.228876 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       0.0794642  0.0144029   5.517 4.06e-08 ***
Primary_AI_ToolClaude 3.5        -0.0136972  0.0111775  -1.225    0.221    
Primary_AI_ToolGemini Pro        -0.0122055  0.0111426  -1.095    0.274    
Primary_AI_ToolGitHub Copilot    -0.0040510  0.0110597  -0.366    0.714    
Primary_AI_ToolPerplexity        -0.0029021  0.0111360  -0.261    0.794    
Task_Frequency_Daily              0.0013383  0.0012032   1.112    0.266    
Main_Usage_CaseCode Debugging     0.0067303  0.0115395   0.583    0.560    
Main_Usage_CaseEssay Drafting    -0.0010976  0.0111765  -0.098    0.922    
Main_Usage_CaseExam Prep         -0.0040764  0.0108443  -0.376    0.707    
Main_Usage_CaseLiterature Review -0.0011514  0.0111168  -0.104    0.918    
Time_Saved_Hours_Weekly           0.0009195  0.0008582   1.071    0.284    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.135 on 1489 degrees of freedom
Multiple R-squared:  0.003985,  Adjusted R-squared:  -0.002704 
F-statistic: 0.5958 on 10 and 1489 DF,  p-value: 0.8185</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_gpa_diff)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 5
   term                              estimate std.error statistic      p.value
   &lt;chr&gt;                                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
 1 (Intercept)                       0.0795    0.0144      5.52   0.0000000406
 2 Primary_AI_ToolClaude 3.5        -0.0137    0.0112     -1.23   0.221       
 3 Primary_AI_ToolGemini Pro        -0.0122    0.0111     -1.10   0.274       
 4 Primary_AI_ToolGitHub Copilot    -0.00405   0.0111     -0.366  0.714       
 5 Primary_AI_ToolPerplexity        -0.00290   0.0111     -0.261  0.794       
 6 Task_Frequency_Daily              0.00134   0.00120     1.11   0.266       
 7 Main_Usage_CaseCode Debugging     0.00673   0.0115      0.583  0.560       
 8 Main_Usage_CaseEssay Drafting    -0.00110   0.0112     -0.0982 0.922       
 9 Main_Usage_CaseExam Prep         -0.00408   0.0108     -0.376  0.707       
10 Main_Usage_CaseLiterature Review -0.00115   0.0111     -0.104  0.918       
11 Time_Saved_Hours_Weekly           0.000919  0.000858    1.07   0.284       </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_gpa_diff, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The model has almost no explanatory power (adjusted R-squared &lt; 1%, p-value is &gt; 0.8).</p>
<p>AI tool, usage frequency, usage case, and time saved do not meaningfully explain GPA change (the coefficients are extremely small and insignificant).</p>
<p>The residual plot shows horizontal bands, confirming the discretized structure of the dependent variable.</p>
<p>In order to solve any issues related to the form of the dependent variable (<code>GPA_Post_AI - GPA_Baseline</code>), and to futher control interpersonal variations, we decided to use in the next model the original GPA scores, with <code>GPA_Post_AI</code> being the new dependent variable.</p>
<hr>
</section>
<section id="adjusted-model-post-ai-gpa-controlled-by-baseline-gpa" class="level5">
<h5 class="anchored" data-anchor-id="adjusted-model-post-ai-gpa-controlled-by-baseline-gpa">Adjusted model: post-AI GPA controlled by baseline GPA</h5>
<div class="callout callout-style-default callout-important callout-titled" title="Why baseline GPA must be controlled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Why baseline GPA must be controlled
</div>
</div>
<div class="callout-body-container callout-body">
<p>The previous model ignores the starting academic level of each student. This is problematic because GPA is bounded: students with a high baseline GPA have less room to improve.</p>
<p>To account for this ceiling effect, post-AI GPA is modeled while controlling for baseline GPA.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>model_gpa_post <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  GPA_Post_AI <span class="sc">~</span> GPA_Baseline <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_gpa_post)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GPA_Post_AI ~ GPA_Baseline + Primary_AI_Tool + Task_Frequency_Daily + 
    Main_Usage_Case + Time_Saved_Hours_Weekly, data = tbl_database)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.230864 -0.100185  0.004172  0.108164  0.240970 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       0.1885454  0.0301075   6.262 4.95e-10 ***
GPA_Baseline                      0.9667125  0.0080809 119.630  &lt; 2e-16 ***
Primary_AI_ToolClaude 3.5        -0.0153904  0.0111257  -1.383    0.167    
Primary_AI_ToolGemini Pro        -0.0119685  0.0110835  -1.080    0.280    
Primary_AI_ToolGitHub Copilot    -0.0055766  0.0110071  -0.507    0.612    
Primary_AI_ToolPerplexity        -0.0040013  0.0110800  -0.361    0.718    
Task_Frequency_Daily              0.0013164  0.0011968   1.100    0.272    
Main_Usage_CaseCode Debugging     0.0074041  0.0114793   0.645    0.519    
Main_Usage_CaseEssay Drafting     0.0008816  0.0111274   0.079    0.937    
Main_Usage_CaseExam Prep         -0.0037176  0.0107870  -0.345    0.730    
Main_Usage_CaseLiterature Review -0.0015371  0.0110581  -0.139    0.889    
Time_Saved_Hours_Weekly           0.0008909  0.0008537   1.044    0.297    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1343 on 1488 degrees of freedom
Multiple R-squared:  0.9064,    Adjusted R-squared:  0.9058 
F-statistic:  1311 on 11 and 1488 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_gpa_post)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
   term                              estimate std.error statistic  p.value
   &lt;chr&gt;                                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)                       0.189     0.0301      6.26   4.95e-10
 2 GPA_Baseline                      0.967     0.00808   120.     0       
 3 Primary_AI_ToolClaude 3.5        -0.0154    0.0111     -1.38   1.67e- 1
 4 Primary_AI_ToolGemini Pro        -0.0120    0.0111     -1.08   2.80e- 1
 5 Primary_AI_ToolGitHub Copilot    -0.00558   0.0110     -0.507  6.12e- 1
 6 Primary_AI_ToolPerplexity        -0.00400   0.0111     -0.361  7.18e- 1
 7 Task_Frequency_Daily              0.00132   0.00120     1.10   2.72e- 1
 8 Main_Usage_CaseCode Debugging     0.00740   0.0115      0.645  5.19e- 1
 9 Main_Usage_CaseEssay Drafting     0.000882  0.0111      0.0792 9.37e- 1
10 Main_Usage_CaseExam Prep         -0.00372   0.0108     -0.345  7.30e- 1
11 Main_Usage_CaseLiterature Review -0.00154   0.0111     -0.139  8.89e- 1
12 Time_Saved_Hours_Weekly           0.000891  0.000854    1.04   2.97e- 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_gpa_post, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This model explains approximately <strong>91% of the variance</strong> in post-AI GPA. However, this explanatory power comes almost entirely from baseline GPA. AI-related variables remain non-significant.</p>
<p>The residual structure shows discretization and a ceiling effect near the maximum GPA value.</p>
<hr>
</section>
<section id="extended-model-adding-age-and-major" class="level5">
<h5 class="anchored" data-anchor-id="extended-model-adding-age-and-major">Extended model: adding <code>Age</code> and <code>Major</code></h5>
<div class="callout callout-style-default callout-tip callout-titled" title="Socio-demographic controls">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Socio-demographic controls
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Do age and major improve the explanatory model?</p>
<p><strong>Method:</strong> The adjusted GPA model is extended with <code>Age</code> and <code>Major</code>.</p>
<p><strong>Interpretation strategy:</strong> This model tests whether socio-demographic variables add meaningful explanatory power beyond baseline GPA and AI usage variables.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model_gpa_post_extended <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  GPA_Post_AI <span class="sc">~</span> GPA_Baseline <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    Major <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_gpa_post_extended)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GPA_Post_AI ~ GPA_Baseline + Age + Major + Primary_AI_Tool + 
    Task_Frequency_Daily + Main_Usage_Case + Time_Saved_Hours_Weekly, 
    data = tbl_database)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.236278 -0.103601  0.004478  0.109158  0.249115 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       0.1438323  0.0448005   3.211  0.00135 ** 
GPA_Baseline                      0.9663385  0.0080912 119.430  &lt; 2e-16 ***
Age                               0.0025006  0.0015133   1.652  0.09867 .  
MajorBusiness Administration     -0.0055656  0.0118780  -0.469  0.63945    
MajorData Science                -0.0107510  0.0118174  -0.910  0.36310    
MajorFine Arts                   -0.0197574  0.0118011  -1.674  0.09430 .  
MajorModern History              -0.0126232  0.0123228  -1.024  0.30582    
MajorSoftware Engineering         0.0067571  0.0120485   0.561  0.57500    
Primary_AI_ToolClaude 3.5        -0.0154836  0.0111413  -1.390  0.16481    
Primary_AI_ToolGemini Pro        -0.0126735  0.0110947  -1.142  0.25351    
Primary_AI_ToolGitHub Copilot    -0.0052856  0.0110174  -0.480  0.63147    
Primary_AI_ToolPerplexity        -0.0045730  0.0110891  -0.412  0.68011    
Task_Frequency_Daily              0.0011796  0.0011983   0.984  0.32509    
Main_Usage_CaseCode Debugging     0.0079924  0.0114779   0.696  0.48633    
Main_Usage_CaseEssay Drafting     0.0013465  0.0111192   0.121  0.90363    
Main_Usage_CaseExam Prep         -0.0029128  0.0107934  -0.270  0.78730    
Main_Usage_CaseLiterature Review -0.0015519  0.0110575  -0.140  0.88841    
Time_Saved_Hours_Weekly           0.0008675  0.0008537   1.016  0.30971    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1341 on 1482 degrees of freedom
Multiple R-squared:  0.907, Adjusted R-squared:  0.9059 
F-statistic: 850.4 on 17 and 1482 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_gpa_post_extended)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   term                              estimate std.error statistic p.value
   &lt;chr&gt;                                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept)                       0.144     0.0448       3.21  0.00135
 2 GPA_Baseline                      0.966     0.00809    119.    0      
 3 Age                               0.00250   0.00151      1.65  0.0987 
 4 MajorBusiness Administration     -0.00557   0.0119      -0.469 0.639  
 5 MajorData Science                -0.0108    0.0118      -0.910 0.363  
 6 MajorFine Arts                   -0.0198    0.0118      -1.67  0.0943 
 7 MajorModern History              -0.0126    0.0123      -1.02  0.306  
 8 MajorSoftware Engineering         0.00676   0.0120       0.561 0.575  
 9 Primary_AI_ToolClaude 3.5        -0.0155    0.0111      -1.39  0.165  
10 Primary_AI_ToolGemini Pro        -0.0127    0.0111      -1.14  0.254  
11 Primary_AI_ToolGitHub Copilot    -0.00529   0.0110      -0.480 0.631  
12 Primary_AI_ToolPerplexity        -0.00457   0.0111      -0.412 0.680  
13 Task_Frequency_Daily              0.00118   0.00120      0.984 0.325  
14 Main_Usage_CaseCode Debugging     0.00799   0.0115       0.696 0.486  
15 Main_Usage_CaseEssay Drafting     0.00135   0.0111       0.121 0.904  
16 Main_Usage_CaseExam Prep         -0.00291   0.0108      -0.270 0.787  
17 Main_Usage_CaseLiterature Review -0.00155   0.0111      -0.140 0.888  
18 Time_Saved_Hours_Weekly           0.000868  0.000854     1.02  0.310  </code></pre>
</div>
</div>
<p>Adding age and major does not substantially improve the model. Baseline GPA remains the dominant predictor. Other effects (notably, of some majors) are weak and should not be overinterpreted without further evidence.</p>
<hr>
</section>
<section id="logistic-model-probability-of-gpa-improvement" class="level5">
<h5 class="anchored" data-anchor-id="logistic-model-probability-of-gpa-improvement">Logistic model: probability of GPA improvement</h5>
<div class="callout callout-style-default callout-tip callout-titled" title="Alternative specification: binary improvement model">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Alternative specification: binary improvement model
</div>
</div>
<div class="callout-body-container callout-body">
<p>Because <code>gpa_diff</code> is a discrete variable, a binary model can be used as a complementary specification.</p>
<p><strong>New dependent variable:</strong> <code>gpa_improved</code>= 1 if <code>gpa_diff</code> &gt; 0, otherwise 0.</p>
<p><strong>Research question:</strong> Which variables predict whether a student improves their GPA?</p>
<p><strong>Method:</strong> Logistic regression is used to model the probability of improvement.</p>
<p><strong>Interpretation:</strong> Coefficients are transformed into odds ratios for readability.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>tbl_database <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gpa_improved =</span> <span class="fu">as.integer</span>(gpa_diff <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>model_gpa_improved <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  gpa_improved <span class="sc">~</span> GPA_Baseline <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    Major <span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_gpa_improved)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = gpa_improved ~ GPA_Baseline + Age + Major + Primary_AI_Tool + 
    Task_Frequency_Daily + Main_Usage_Case + Time_Saved_Hours_Weekly, 
    family = binomial, data = tbl_database)

Coefficients:
                                  Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)                      -0.277363   0.683021  -0.406   0.6847  
GPA_Baseline                      0.138756   0.123461   1.124   0.2611  
Age                               0.013574   0.023103   0.588   0.5568  
MajorBusiness Administration     -0.070015   0.183263  -0.382   0.7024  
MajorData Science                -0.120063   0.181749  -0.661   0.5089  
MajorFine Arts                   -0.400617   0.179785  -2.228   0.0259 *
MajorModern History              -0.255229   0.188403  -1.355   0.1755  
MajorSoftware Engineering        -0.070086   0.185833  -0.377   0.7061  
Primary_AI_ToolClaude 3.5        -0.103141   0.170090  -0.606   0.5443  
Primary_AI_ToolGemini Pro        -0.080663   0.169692  -0.475   0.6345  
Primary_AI_ToolGitHub Copilot    -0.081593   0.168486  -0.484   0.6282  
Primary_AI_ToolPerplexity        -0.049209   0.169915  -0.290   0.7721  
Task_Frequency_Daily              0.023526   0.018293   1.286   0.1984  
Main_Usage_CaseCode Debugging     0.104446   0.176460   0.592   0.5539  
Main_Usage_CaseEssay Drafting    -0.016993   0.169949  -0.100   0.9204  
Main_Usage_CaseExam Prep         -0.099723   0.164334  -0.607   0.5440  
Main_Usage_CaseLiterature Review -0.076586   0.168355  -0.455   0.6492  
Time_Saved_Hours_Weekly           0.004384   0.013028   0.337   0.7365  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2023.8  on 1499  degrees of freedom
Residual deviance: 2010.9  on 1482  degrees of freedom
AIC: 2046.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>gpa_improved_results <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_gpa_improved) <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">odds_ratio =</span> <span class="fu">exp</span>(estimate)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>gpa_improved_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 6
   term                          estimate std.error statistic p.value odds_ratio
   &lt;chr&gt;                            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
 1 (Intercept)                   -0.277      0.683    -0.406   0.685       0.758
 2 GPA_Baseline                   0.139      0.123     1.12    0.261       1.15 
 3 Age                            0.0136     0.0231    0.588   0.557       1.01 
 4 MajorBusiness Administration  -0.0700     0.183    -0.382   0.702       0.932
 5 MajorData Science             -0.120      0.182    -0.661   0.509       0.887
 6 MajorFine Arts                -0.401      0.180    -2.23    0.0259      0.670
 7 MajorModern History           -0.255      0.188    -1.35    0.176       0.775
 8 MajorSoftware Engineering     -0.0701     0.186    -0.377   0.706       0.932
 9 Primary_AI_ToolClaude 3.5     -0.103      0.170    -0.606   0.544       0.902
10 Primary_AI_ToolGemini Pro     -0.0807     0.170    -0.475   0.635       0.923
11 Primary_AI_ToolGitHub Copilot -0.0816     0.168    -0.484   0.628       0.922
12 Primary_AI_ToolPerplexity     -0.0492     0.170    -0.290   0.772       0.952
13 Task_Frequency_Daily           0.0235     0.0183    1.29    0.198       1.02 
14 Main_Usage_CaseCode Debugging  0.104      0.176     0.592   0.554       1.11 
15 Main_Usage_CaseEssay Drafting -0.0170     0.170    -0.1000  0.920       0.983
16 Main_Usage_CaseExam Prep      -0.0997     0.164    -0.607   0.544       0.905
17 Main_Usage_CaseLiterature Re… -0.0766     0.168    -0.455   0.649       0.926
18 Time_Saved_Hours_Weekly        0.00438    0.0130    0.337   0.736       1.00 </code></pre>
</div>
</div>
<p>The logistic model does not reveal robust predictors of GPA improvement. Fine Arts students show lower odds of improvement compared with Biology students (33%, with p-value = 0.02), but this isolated effect should be interpreted cautiously.</p>
<hr>
</section>
</section>
</section>
<section id="sec-career-confidence" class="level3">
<h3 class="anchored" data-anchor-id="sec-career-confidence">Career confidence</h3>
<p>Let’s turn to a different kind of outcome: career confidence. This variable does not measure academic performance directly. Instead, it captures a subjective perception of future readiness for career.</p>
<section id="correlations-with-gpa-metrics" class="level4">
<h4 class="anchored" data-anchor-id="correlations-with-gpa-metrics">Correlations with GPA metrics</h4>
<div class="callout callout-style-default callout-tip callout-titled" title="Correlation analysis">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Correlation analysis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Is career confidence associated with GPA baseline, post-AI GPA, or GPA change?</p>
<p><strong>Methods:</strong> <em>Pearson</em> correlations are used for linear relationships. <em>Spearman</em> and <em>Kendall</em> correlations are added as robustness checks because both GPA and confidence scores are discrete variables.</p>
<p><strong>Interpretation:</strong> If all correlations remain close to zero, there is no meaningful continuous or monotonic relationship to report.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>career_gpa_cor_pearson <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cor_baseline =</span> <span class="fu">cor</span>(GPA_Baseline, Career_Confidence_Score),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cor_post =</span> <span class="fu">cor</span>(GPA_Post_AI, Career_Confidence_Score),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cor_diff =</span> <span class="fu">cor</span>(gpa_diff, Career_Confidence_Score)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>career_gpa_cor_spearman <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"GPA_Baseline"</span>, <span class="st">"GPA_Post_AI"</span>, <span class="st">"gpa_diff"</span>),</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">correlation =</span> <span class="fu">c</span>(</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(tbl_database<span class="sc">$</span>GPA_Baseline, tbl_database<span class="sc">$</span>Career_Confidence_Score, <span class="at">method =</span> <span class="st">"spearman"</span>),</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(tbl_database<span class="sc">$</span>GPA_Post_AI, tbl_database<span class="sc">$</span>Career_Confidence_Score, <span class="at">method =</span> <span class="st">"spearman"</span>),</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(tbl_database<span class="sc">$</span>gpa_diff, tbl_database<span class="sc">$</span>Career_Confidence_Score, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>career_gpa_cor_kendall <span class="ot">&lt;-</span> <span class="fu">cor</span>(</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>  tbl_database<span class="sc">$</span>gpa_diff,</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>  tbl_database<span class="sc">$</span>Career_Confidence_Score,</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"kendall"</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>career_by_gpa_improvement <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gpa_improved) <span class="sc">|&gt;</span></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_confidence =</span> <span class="fu">mean</span>(Career_Confidence_Score))</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>career_gpa_cor_pearson</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  cor_baseline cor_post cor_diff
         &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1       0.0189   0.0214  0.00909</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>career_gpa_cor_spearman</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  variable     correlation
  &lt;chr&gt;              &lt;dbl&gt;
1 GPA_Baseline      0.0172
2 GPA_Post_AI       0.0199
3 gpa_diff          0.0134</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>career_gpa_cor_kendall</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0096842</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>career_by_gpa_improvement</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  gpa_improved mean_confidence
         &lt;int&gt;           &lt;dbl&gt;
1            0            5.25
2            1            5.53</code></pre>
</div>
</div>
<p>Pearson, Spearman, and Kendall correlations are all close to zero (&lt;0.03). Career confidence is therefore not meaningfully associated with baseline GPA, post-AI GPA, or GPA change.</p>
<p>Students who improved their GPA have slightly higher average confidence (<code>5.53</code> vs.&nbsp;<code>5.25</code>, a difference of 0.28 points), but the impact is very modest.</p>
</section>
<section id="distribution-of-career-confidence" class="level4">
<h4 class="anchored" data-anchor-id="distribution-of-career-confidence">Distribution of career confidence</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(tbl_database<span class="sc">$</span>Career_Confidence_Score)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(tbl_database<span class="sc">$</span>Career_Confidence_Score, <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>plot_career_confidence_hist <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Career_Confidence_Score)) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#4C78A8"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Histogram of Career Confidence Score"</span>,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Scores"</span>,</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of occurences"</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>plot_career_confidence_hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Career confidence is evidently a discrete variable evenly distributed, suggesting limited internal structure to exploit for analysis purposes.</p>
</section>
<section id="career-confidence-model" class="level4">
<h4 class="anchored" data-anchor-id="career-confidence-model">Career confidence model</h4>
<div class="callout callout-style-default callout-tip callout-titled" title="OLS model on career confidence">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>OLS model on career confidence
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Can GPA, AI usage variables, age, and major explain career confidence?</p>
<p><strong>Dependent variable:</strong> <code>Career_Confidence_Score</code></p>
<p><strong>Method:</strong> OLS regression is used as an approximation. Although the variable is discrete, it has ten levels, which allows a simple exploratory linear model.</p>
<p><strong>Interpretation:</strong> The model is evaluated globally using the F-test and R², not only individual p-values.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>model_career_confidence <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  Career_Confidence_Score <span class="sc">~</span> GPA_Post_AI <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    Major <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_career_confidence)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Career_Confidence_Score ~ GPA_Post_AI + Age + Major + 
    Primary_AI_Tool + Task_Frequency_Daily + Main_Usage_Case + 
    Time_Saved_Hours_Weekly, data = tbl_database)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.2533 -2.4065 -0.0373  2.4108  5.4112 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       3.8616993  0.9467845   4.079 4.77e-05 ***
GPA_Post_AI                       0.1796790  0.1686962   1.065   0.2870    
Age                               0.0171094  0.0320432   0.534   0.5935    
MajorBusiness Administration      0.5140325  0.2514553   2.044   0.0411 *  
MajorData Science                 0.5377438  0.2502101   2.149   0.0318 *  
MajorFine Arts                    0.4771587  0.2499575   1.909   0.0565 .  
MajorModern History              -0.0635168  0.2608791  -0.243   0.8077    
MajorSoftware Engineering         0.1603435  0.2549663   0.629   0.5295    
Primary_AI_ToolClaude 3.5         0.1379495  0.2359276   0.585   0.5588    
Primary_AI_ToolGemini Pro        -0.1991727  0.2348535  -0.848   0.3965    
Primary_AI_ToolGitHub Copilot    -0.0345151  0.2332363  -0.148   0.8824    
Primary_AI_ToolPerplexity         0.3222097  0.2347488   1.373   0.1701    
Task_Frequency_Daily              0.0234167  0.0253661   0.923   0.3561    
Main_Usage_CaseCode Debugging     0.1728065  0.2429880   0.711   0.4771    
Main_Usage_CaseEssay Drafting     0.0680385  0.2353637   0.289   0.7726    
Main_Usage_CaseExam Prep          0.3322711  0.2284713   1.454   0.1461    
Main_Usage_CaseLiterature Review  0.0426863  0.2340688   0.182   0.8553    
Time_Saved_Hours_Weekly           0.0007358  0.0180708   0.041   0.9675    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.84 on 1482 degrees of freedom
Multiple R-squared:  0.01509,   Adjusted R-squared:  0.003796 
F-statistic: 1.336 on 17 and 1482 DF,  p-value: 0.1609</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_career_confidence)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   term                              estimate std.error statistic   p.value
   &lt;chr&gt;                                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)                       3.86        0.947     4.08   0.0000477
 2 GPA_Post_AI                       0.180       0.169     1.07   0.287    
 3 Age                               0.0171      0.0320    0.534  0.593    
 4 MajorBusiness Administration      0.514       0.251     2.04   0.0411   
 5 MajorData Science                 0.538       0.250     2.15   0.0318   
 6 MajorFine Arts                    0.477       0.250     1.91   0.0565   
 7 MajorModern History              -0.0635      0.261    -0.243  0.808    
 8 MajorSoftware Engineering         0.160       0.255     0.629  0.530    
 9 Primary_AI_ToolClaude 3.5         0.138       0.236     0.585  0.559    
10 Primary_AI_ToolGemini Pro        -0.199       0.235    -0.848  0.397    
11 Primary_AI_ToolGitHub Copilot    -0.0345      0.233    -0.148  0.882    
12 Primary_AI_ToolPerplexity         0.322       0.235     1.37   0.170    
13 Task_Frequency_Daily              0.0234      0.0254    0.923  0.356    
14 Main_Usage_CaseCode Debugging     0.173       0.243     0.711  0.477    
15 Main_Usage_CaseEssay Drafting     0.0680      0.235     0.289  0.773    
16 Main_Usage_CaseExam Prep          0.332       0.228     1.45   0.146    
17 Main_Usage_CaseLiterature Review  0.0427      0.234     0.182  0.855    
18 Time_Saved_Hours_Weekly           0.000736    0.0181    0.0407 0.968    </code></pre>
</div>
</div>
<p>The model is not globally significant and explains only a very small share of variance. Some major-level effects appear, but they should not be overinterpreted.</p>
<hr>
</section>
</section>
<section id="sec-ai-usage" class="level3">
<h3 class="anchored" data-anchor-id="sec-ai-usage">AI usage and adoption</h3>
<p>At this point, our analysis changes direction. Instead of asking whether AI usage affects outcomes, I test whether baseline academic performance predicts AI usage.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Inverted model: who uses AI more frequently?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Inverted model: who uses AI more frequently?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Do students with lower baseline GPA use AI more frequently?</p>
<p><strong>Null hypothesis (H0):</strong> Baseline GPA, age, and major do not predict AI usage frequency.</p>
<p><strong>Alternative hypothesis (H1):</strong> At least one of these variables predicts AI usage frequency.</p>
<p><strong>Method:</strong> OLS regression is used with <code>Task_Frequency_Daily</code> as the dependent variable.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>model_usage_from_gpa <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  Task_Frequency_Daily <span class="sc">~</span> GPA_Baseline <span class="sc">+</span> Age <span class="sc">+</span> Major,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_usage_from_gpa)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Task_Frequency_Daily ~ GPA_Baseline + Age + Major, 
    data = tbl_database)

Residuals:
   Min     1Q Median     3Q    Max 
-4.755 -2.523 -0.185  2.595  4.912 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   4.77620    0.92605   5.158 2.84e-07 ***
GPA_Baseline                 -0.02615    0.17478  -0.150   0.8811    
Age                           0.02361    0.03272   0.721   0.4708    
MajorBusiness Administration  0.34410    0.25639   1.342   0.1798    
MajorData Science             0.13653    0.25561   0.534   0.5933    
MajorFine Arts               -0.01068    0.25486  -0.042   0.9666    
MajorModern History           0.35367    0.26630   1.328   0.1844    
MajorSoftware Engineering     0.47325    0.26031   1.818   0.0693 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.906 on 1492 degrees of freedom
Multiple R-squared:  0.004404,  Adjusted R-squared:  -0.0002669 
F-statistic: 0.9429 on 7 and 1492 DF,  p-value: 0.4721</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_usage_from_gpa)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term                         estimate std.error statistic     p.value
  &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1 (Intercept)                    4.78      0.926     5.16   0.000000284
2 GPA_Baseline                  -0.0262    0.175    -0.150  0.881      
3 Age                            0.0236    0.0327    0.721  0.471      
4 MajorBusiness Administration   0.344     0.256     1.34   0.180      
5 MajorData Science              0.137     0.256     0.534  0.593      
6 MajorFine Arts                -0.0107    0.255    -0.0419 0.967      
7 MajorModern History            0.354     0.266     1.33   0.184      
8 MajorSoftware Engineering      0.473     0.260     1.82   0.0693     </code></pre>
</div>
</div>
<p>There is no evidence that baseline GPA predicts AI usage frequency.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Binary high-usage model">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Binary high-usage model
</div>
</div>
<div class="callout-body-container callout-body">
<p>A binary version of AI usage is also tested.</p>
<p>Students above the median frequency of daily AI use are classified as high users.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>tbl_database <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">high_usage =</span> Task_Frequency_Daily <span class="sc">&gt;</span> <span class="fu">median</span>(Task_Frequency_Daily))</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>model_high_usage <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  high_usage <span class="sc">~</span> GPA_Baseline <span class="sc">+</span> Age <span class="sc">+</span> Major,</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database,</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_high_usage)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = high_usage ~ GPA_Baseline + Age + Major, family = binomial, 
    data = tbl_database)

Coefficients:
                              Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                  -0.499463   0.639385  -0.781    0.435
GPA_Baseline                 -0.006911   0.120634  -0.057    0.954
Age                           0.014459   0.022586   0.640    0.522
MajorBusiness Administration  0.286908   0.177035   1.621    0.105
MajorData Science             0.032606   0.176782   0.184    0.854
MajorFine Arts                0.036932   0.176251   0.210    0.834
MajorModern History           0.150300   0.183831   0.818    0.414
MajorSoftware Engineering     0.278997   0.179718   1.552    0.121

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2076.9  on 1499  degrees of freedom
Residual deviance: 2071.3  on 1492  degrees of freedom
AIC: 2087.3

Number of Fisher Scoring iterations: 3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_high_usage)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term                         estimate std.error statistic p.value
  &lt;chr&gt;                           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)                  -0.499      0.639    -0.781    0.435
2 GPA_Baseline                 -0.00691    0.121    -0.0573   0.954
3 Age                           0.0145     0.0226    0.640    0.522
4 MajorBusiness Administration  0.287      0.177     1.62     0.105
5 MajorData Science             0.0326     0.177     0.184    0.854
6 MajorFine Arts                0.0369     0.176     0.210    0.834
7 MajorModern History           0.150      0.184     0.818    0.414
8 MajorSoftware Engineering     0.279      0.180     1.55     0.121</code></pre>
</div>
</div>
<p>The binary model confirms the same result: high AI usage is not meaningfully predicted by GPA, age, or major.</p>
<hr>
</section>
<section id="sec-ethics" class="level3">
<h3 class="anchored" data-anchor-id="sec-ethics">Ethical concerns</h3>
<p>Ethical concern is an ordinal variable. Therefore, an ordered logistic regression is more appropriate than a standard linear model.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Ordered logistic regression">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Ordered logistic regression
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Are ethical concerns structured by AI usage behavior?</p>
<p><strong>Dependent variable:</strong> <code>AI_Ethics_Concern</code></p>
<p><strong>Method:</strong> An ordered logistic regression is used because ethical concern has ordered categories.</p>
<p><strong>Interpretation:</strong> Odds ratios greater than 1 indicate higher odds of being in a higher concern category. Odds ratios below 1 indicate lower odds.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>model_ethics_concern <span class="ot">&lt;-</span> <span class="fu">polr</span>(</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  AI_Ethics_Concern <span class="sc">~</span> Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">+</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    Major,</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Hess =</span> <span class="cn">TRUE</span></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>ethics_concern_results <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_ethics_concern) <span class="sc">|&gt;</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fu">abs</span>(statistic)),</span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">odds_ratio =</span> <span class="fu">exp</span>(estimate)</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>model_ethics_concern</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = AI_Ethics_Concern ~ Primary_AI_Tool + Task_Frequency_Daily + 
    Main_Usage_Case + Time_Saved_Hours_Weekly + Age + Major, 
    data = tbl_database, Hess = TRUE)

Coefficients:
       Primary_AI_ToolClaude 3.5        Primary_AI_ToolGemini Pro 
                     0.111868419                     -0.028376443 
   Primary_AI_ToolGitHub Copilot        Primary_AI_ToolPerplexity 
                    -0.012916458                     -0.038564835 
            Task_Frequency_Daily    Main_Usage_CaseCode Debugging 
                    -0.034251244                      0.063444287 
   Main_Usage_CaseEssay Drafting         Main_Usage_CaseExam Prep 
                    -0.134404998                      0.092073498 
Main_Usage_CaseLiterature Review          Time_Saved_Hours_Weekly 
                    -0.128376308                      0.008266361 
                             Age     MajorBusiness Administration 
                    -0.012945178                      0.133444901 
               MajorData Science                   MajorFine Arts 
                    -0.031473215                     -0.107609806 
             MajorModern History        MajorSoftware Engineering 
                    -0.129259211                     -0.012092017 

Intercepts:
  High|Low Low|Medium 
 -1.140778   0.325853 

Residual Deviance: 3280.351 
AIC: 3316.351 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ethics_concern_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 7
   term                estimate std.error statistic coef.type p_value odds_ratio
   &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;      &lt;dbl&gt;
 1 Primary_AI_ToolCla…  0.112      0.153     0.733  coeffici…  0.464       1.12 
 2 Primary_AI_ToolGem… -0.0284     0.152    -0.186  coeffici…  0.852       0.972
 3 Primary_AI_ToolGit… -0.0129     0.152    -0.0851 coeffici…  0.932       0.987
 4 Primary_AI_ToolPer… -0.0386     0.153    -0.252  coeffici…  0.801       0.962
 5 Task_Frequency_Dai… -0.0343     0.0165   -2.08   coeffici…  0.0379      0.966
 6 Main_Usage_CaseCod…  0.0634     0.160     0.398  coeffici…  0.691       1.07 
 7 Main_Usage_CaseEss… -0.134      0.152    -0.882  coeffici…  0.378       0.874
 8 Main_Usage_CaseExa…  0.0921     0.149     0.619  coeffici…  0.536       1.10 
 9 Main_Usage_CaseLit… -0.128      0.152    -0.843  coeffici…  0.399       0.880
10 Time_Saved_Hours_W…  0.00827    0.0117    0.704  coeffici…  0.482       1.01 
11 Age                 -0.0129     0.0207   -0.626  coeffici…  0.531       0.987
12 MajorBusiness Admi…  0.133      0.162     0.824  coeffici…  0.410       1.14 
13 MajorData Science   -0.0315     0.162    -0.195  coeffici…  0.846       0.969
14 MajorFine Arts      -0.108      0.162    -0.665  coeffici…  0.506       0.898
15 MajorModern History -0.129      0.168    -0.771  coeffici…  0.441       0.879
16 MajorSoftware Engi… -0.0121     0.165    -0.0734 coeffici…  0.942       0.988
17 High|Low            -1.14       0.495    -2.30   scale      0.0212      0.320
18 Low|Medium           0.326      0.494     0.659  scale      0.510       1.39 </code></pre>
</div>
</div>
<p>Daily AI usage shows a weak negative association with ethical concern. The odds ratio is approximately <code>0.97</code>, suggesting a small decrease in the probability (<code>3%</code>) of reporting higher ethical concern as usage frequency increases.</p>
<p>This <strong>effect of familiarity</strong> is statistically detectable but small. Overall, ethical concern is not strongly structured by AI tool, usage case, time saved, age, or major.</p>
<hr>
</section>
<section id="sec-time-saved" class="level3">
<h3 class="anchored" data-anchor-id="sec-time-saved">Time saved</h3>
<p>Time saved is intuitively expected to be the variable most directly connected to AI usage. This makes it an important test case.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(tbl_database<span class="sc">$</span>Time_Saved_Hours_Weekly)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(tbl_database<span class="sc">$</span>Time_Saved_Hours_Weekly, <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>plot_time_saved_hist <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Time_Saved_Hours_Weekly)) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"#4C78A8"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Histogram of Time Saved Weekly"</span>,</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hours"</span>,</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of occurences"</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>plot_time_saved_hist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projects_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="OLS model on time saved">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>OLS model on time saved
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Which variables explain perceived weekly time saved?</p>
<p><strong>Dependent variable:</strong> <code>Time_Saved_Hours_Weekly</code></p>
<p><strong>Method:</strong> OLS regression is used to test whether usage frequency, usage case, AI tool, GPA, age, or major explain time saved.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>model_time_saved <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  Time_Saved_Hours_Weekly <span class="sc">~</span> Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>    Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>    GPA_Baseline <span class="sc">+</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>    Age <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>    Major,</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_time_saved)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Time_Saved_Hours_Weekly ~ Task_Frequency_Daily + 
    Main_Usage_Case + Primary_AI_Tool + GPA_Baseline + Age + 
    Major, data = tbl_database)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.3425 -3.5576  0.0361  3.5588  7.1058 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       8.643878   1.344104   6.431 1.71e-10 ***
Task_Frequency_Daily             -0.014488   0.036448  -0.397    0.691    
Main_Usage_CaseCode Debugging    -0.319302   0.349030  -0.915    0.360    
Main_Usage_CaseEssay Drafting     0.147583   0.338197   0.436    0.663    
Main_Usage_CaseExam Prep         -0.157124   0.328282  -0.479    0.632    
Main_Usage_CaseLiterature Review -0.161804   0.336315  -0.481    0.631    
Primary_AI_ToolClaude 3.5        -0.052744   0.338887  -0.156    0.876    
Primary_AI_ToolGemini Pro         0.311750   0.337375   0.924    0.356    
Primary_AI_ToolGitHub Copilot     0.119346   0.335107   0.356    0.722    
Primary_AI_ToolPerplexity         0.501912   0.337051   1.489    0.137    
GPA_Baseline                     -0.075141   0.246108  -0.305    0.760    
Age                               0.001518   0.046032   0.033    0.974    
MajorBusiness Administration      0.309237   0.361211   0.856    0.392    
MajorData Science                 0.293442   0.359375   0.817    0.414    
MajorFine Arts                   -0.212726   0.358918  -0.593    0.553    
MajorModern History               0.046838   0.374827   0.125    0.901    
MajorSoftware Engineering         0.005646   0.366485   0.015    0.988    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.08 on 1483 degrees of freedom
Multiple R-squared:  0.006385,  Adjusted R-squared:  -0.004335 
F-statistic: 0.5956 on 16 and 1483 DF,  p-value: 0.8894</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_time_saved)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 5
   term                             estimate std.error statistic  p.value
   &lt;chr&gt;                               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)                       8.64       1.34      6.43   1.71e-10
 2 Task_Frequency_Daily             -0.0145     0.0364   -0.397  6.91e- 1
 3 Main_Usage_CaseCode Debugging    -0.319      0.349    -0.915  3.60e- 1
 4 Main_Usage_CaseEssay Drafting     0.148      0.338     0.436  6.63e- 1
 5 Main_Usage_CaseExam Prep         -0.157      0.328    -0.479  6.32e- 1
 6 Main_Usage_CaseLiterature Review -0.162      0.336    -0.481  6.31e- 1
 7 Primary_AI_ToolClaude 3.5        -0.0527     0.339    -0.156  8.76e- 1
 8 Primary_AI_ToolGemini Pro         0.312      0.337     0.924  3.56e- 1
 9 Primary_AI_ToolGitHub Copilot     0.119      0.335     0.356  7.22e- 1
10 Primary_AI_ToolPerplexity         0.502      0.337     1.49   1.37e- 1
11 GPA_Baseline                     -0.0751     0.246    -0.305  7.60e- 1
12 Age                               0.00152    0.0460    0.0330 9.74e- 1
13 MajorBusiness Administration      0.309      0.361     0.856  3.92e- 1
14 MajorData Science                 0.293      0.359     0.817  4.14e- 1
15 MajorFine Arts                   -0.213      0.359    -0.593  5.53e- 1
16 MajorModern History               0.0468     0.375     0.125  9.01e- 1
17 MajorSoftware Engineering         0.00565    0.366     0.0154 9.88e- 1</code></pre>
</div>
</div>
<p>The model does not identify meaningful predictors of weekly time saved. This is notable because time saved is intuitively expected to be linked to usage frequency, but the data does not support that relationship.</p>
<p>There are two possible explanations for these results: either the self-reported measurement are biased, or the dataset has been constructed artificially with no relationship whatsoever to the field observations.</p>
<hr>
</section>
<section id="sec-clustering" class="level3">
<h3 class="anchored" data-anchor-id="sec-clustering">Clustering</h3>
<section id="finding-clusters-in-the-data" class="level4">
<h4 class="anchored" data-anchor-id="finding-clusters-in-the-data">Finding clusters in the data</h4>
<p>Rather than testing linear relationships only, the final step of the analysis explores whether latent profiles of students emerge from the joint distribution of academic performance, AI usage, and perceived outcomes.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="K-means clustering">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>K-means clustering
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Can students be grouped into distinct profiles combining academic performance, AI usage, and perceived outcomes?</p>
<p><strong>Method:</strong> K-means clustering is applied to standardized numerical variables.</p>
<p><strong>Variables used:</strong></p>
<ul>
<li><code>Task_Frequency_Daily</code></li>
<li><code>Time_Saved_Hours_Weekly</code></li>
<li><code>Career_Confidence_Score</code></li>
<li><code>GPA_Baseline</code></li>
<li><code>gpa_diff</code>.</li>
</ul>
<p><strong>Reason for scaling:</strong> Variables are measured on different scales. Standardization ensures that each variable contributes equally to the clustering algorithm.</p>
<p><strong>Important limitation:</strong> Because GPA variables are included in the clustering process, the resulting clusters partially reflect outcome structure. They must therefore be interpreted as descriptive profiles, not causal groups.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>clustering_data <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>    Career_Confidence_Score,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    GPA_Baseline,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>    gpa_diff</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale</span>()</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1999</span>)</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>kmeans_model <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>  clustering_data,</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">centers =</span> <span class="dv">3</span>,</span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">nstart =</span> <span class="dv">25</span></span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb81-18"><a href="#cb81-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-19"><a href="#cb81-19" aria-hidden="true" tabindex="-1"></a>tbl_database<span class="sc">$</span>cluster <span class="ot">&lt;-</span> <span class="fu">factor</span>(kmeans_model<span class="sc">$</span>cluster)</span>
<span id="cb81-20"><a href="#cb81-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-21"><a href="#cb81-21" aria-hidden="true" tabindex="-1"></a>cluster_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(tbl_database<span class="sc">$</span>cluster)</span>
<span id="cb81-22"><a href="#cb81-22" aria-hidden="true" tabindex="-1"></a>cluster_proportions <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(<span class="fu">table</span>(tbl_database<span class="sc">$</span>cluster))</span>
<span id="cb81-23"><a href="#cb81-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-24"><a href="#cb81-24" aria-hidden="true" tabindex="-1"></a>cluster_profiles <span class="ot">&lt;-</span> tbl_database <span class="sc">|&gt;</span></span>
<span id="cb81-25"><a href="#cb81-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster) <span class="sc">|&gt;</span></span>
<span id="cb81-26"><a href="#cb81-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb81-27"><a href="#cb81-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb81-28"><a href="#cb81-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_usage =</span> <span class="fu">mean</span>(Task_Frequency_Daily),</span>
<span id="cb81-29"><a href="#cb81-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_time_saved =</span> <span class="fu">mean</span>(Time_Saved_Hours_Weekly),</span>
<span id="cb81-30"><a href="#cb81-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_confidence =</span> <span class="fu">mean</span>(Career_Confidence_Score),</span>
<span id="cb81-31"><a href="#cb81-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_gpa_baseline =</span> <span class="fu">mean</span>(GPA_Baseline),</span>
<span id="cb81-32"><a href="#cb81-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_gpa_diff =</span> <span class="fu">mean</span>(gpa_diff)</span>
<span id="cb81-33"><a href="#cb81-33" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb81-34"><a href="#cb81-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-35"><a href="#cb81-35" aria-hidden="true" tabindex="-1"></a>cluster_counts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3 
534 540 426 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>cluster_proportions</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3 
0.356 0.360 0.284 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cluster_profiles, <span class="at">width =</span> <span class="cn">Inf</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  cluster     n mean_usage mean_time_saved mean_confidence mean_gpa_baseline
  &lt;fct&gt;   &lt;int&gt;      &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
1 1         534       5.57            9.24            5.62              3.07
2 2         540       5.21            8.55            5.46              3.71
3 3         426       5.46            7.54            5.11              2.92
  mean_gpa_diff
          &lt;dbl&gt;
1        0.229 
2        0.0353
3       -0.0232</code></pre>
</div>
</div>
<p>The algorithm produces three balanced groups:</p>
<ul>
<li>Cluster 1: 534 observations (<code>~35.6%</code>)</li>
<li>Cluster 2: 540 observations (<code>~36.0%</code>)</li>
<li>Cluster 3: 426 observations (<code>~28.4%</code>)</li>
</ul>
<p>The distribution suggests no dominant group and indicates a relatively homogeneous partitioning of the dataset.</p>
<p>K-means clustering produces balanced groups, but the profiles are only weakly differentiated. The main differences come from GPA baseline and GPA difference rather than from AI usage behavior.</p>
<ol type="1">
<li>Cluster 1 — “improvers”</li>
</ol>
<ul>
<li>average GPA (3.07)</li>
<li>strong GPA gain (+0.23)</li>
<li>most active users (5.57 tasks run daily)</li>
<li>highest time saved (9.24 hours per week)</li>
<li>highest confidence (5.62)</li>
</ul>
<p>Students in this group exhibit the strongest performance gains. Their intermediate baseline level suggests sufficient skills to leverage AI outputs effectively, combined with a substantial margin for improvement.</p>
<p>AI usage appears here as a <strong>complementary resource</strong>, supporting learning and performance.</p>
<ol start="2" type="1">
<li>Cluster 2 — “high baseline, stable”</li>
</ol>
<ul>
<li>high baseline GPA (3.71)</li>
<li>low gain (+0.04)</li>
<li>the lowest daily usage (5.21 tasks per day)</li>
<li>average time saved (8.55 hours per week)</li>
<li>average confidence score (5.46)</li>
</ul>
<p>These students are already near the upper bound of the GPA scale. The limited improvement is consistent with a <strong>ceiling effect</strong>, which mechanically restricts potential gains.</p>
<p>AI usage appears more <strong>selective and marginal</strong>, with limited observable impact on outcomes.</p>
<ol start="3" type="1">
<li>Cluster 3 — “low performers, low gains”</li>
</ol>
<ul>
<li>low baseline GPA (2.92)</li>
<li>slight decline (negative gpa_diff of -0.02)</li>
<li>average usage frequency (5.46 tasks per day)</li>
<li>less time saved (7.54 hours per week)</li>
<li>lower confidence score (5.11)</li>
</ul>
<p>Despite comparable usage levels, this group does not benefit from AI. The absence of gains suggests a <strong>misalignment between tool usage and underlying skills</strong>.</p>
<p>AI may function here as a <strong>substitute rather than an augmentation mechanism</strong>, leading to limited or even negative outcomes.</p>
<p><strong>Otherwise stated:</strong></p>
<p>The students with average baseline GPA score gained the most from AI usage, both on GPA and career confidence score, being the most active users and saving more time than the two other groups. Therefore, they are called “improvers”.</p>
<p>The students with higher baseline GPA gained very little from AI usage, their engagement with AI tools being generally moderate if not lower than in other groups.</p>
<p>However, students with lower GPA baseline score did not gain anything from AI tools if not the lowest career confidence score and worse GPA results. They use AI tools almost as frequently as “improvers”, but they gain less from the tools than any other group.</p>
</section>
<section id="sec-clustering-ols" class="level4">
<h4 class="anchored" data-anchor-id="sec-clustering-ols">Cluster integration into GPA model</h4>
<p>To test whether these latent profiles capture additional variation in academic outcomes, cluster membership is introduced into the GPA model.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Cluster-based regression: interpretation caution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Cluster-based regression: interpretation caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Objective:</strong> Assess whether cluster membership explains variation in post-AI GPA beyond baseline GPA and observed variables.</p>
<p><strong>Important limitation:</strong> Clusters are constructed using variables directly related to GPA outcomes. Therefore, their effect in regression models reflects latent structure already present in the data, not an independent causal mechanism.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>model_cluster_gpa <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  GPA_Post_AI <span class="sc">~</span> GPA_Baseline <span class="sc">+</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>    cluster <span class="sc">+</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>    Primary_AI_Tool <span class="sc">+</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>    Task_Frequency_Daily <span class="sc">+</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>    Main_Usage_Case <span class="sc">+</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>    Time_Saved_Hours_Weekly,</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> tbl_database</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cluster_gpa)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = GPA_Post_AI ~ GPA_Baseline + cluster + Primary_AI_Tool + 
    Task_Frequency_Daily + Main_Usage_Case + Time_Saved_Hours_Weekly, 
    data = tbl_database)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.160164 -0.054016 -0.008036  0.062780  0.214356 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       2.245e-01  2.628e-02   8.541  &lt; 2e-16 ***
GPA_Baseline                      1.011e+00  7.956e-03 127.079  &lt; 2e-16 ***
cluster2                         -2.036e-01  7.036e-03 -28.936  &lt; 2e-16 ***
cluster3                         -2.565e-01  5.435e-03 -47.202  &lt; 2e-16 ***
Primary_AI_ToolClaude 3.5         1.529e-03  6.643e-03   0.230    0.818    
Primary_AI_ToolGemini Pro        -6.038e-03  6.610e-03  -0.913    0.361    
Primary_AI_ToolGitHub Copilot    -6.872e-03  6.565e-03  -1.047    0.295    
Primary_AI_ToolPerplexity        -9.901e-04  6.607e-03  -0.150    0.881    
Task_Frequency_Daily              8.647e-05  7.157e-04   0.121    0.904    
Main_Usage_CaseCode Debugging    -6.910e-05  6.849e-03  -0.010    0.992    
Main_Usage_CaseEssay Drafting     7.355e-03  6.637e-03   1.108    0.268    
Main_Usage_CaseExam Prep          1.467e-03  6.433e-03   0.228    0.820    
Main_Usage_CaseLiterature Review  2.044e-03  6.596e-03   0.310    0.757    
Time_Saved_Hours_Weekly          -3.154e-03  5.171e-04  -6.100 1.35e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.08007 on 1486 degrees of freedom
Multiple R-squared:  0.9668,    Adjusted R-squared:  0.9665 
F-statistic:  3327 on 13 and 1486 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_cluster_gpa)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 5
   term                               estimate std.error statistic   p.value
   &lt;chr&gt;                                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)                       0.224      0.0263      8.54   3.24e- 17
 2 GPA_Baseline                      1.01       0.00796   127.     0        
 3 cluster2                         -0.204      0.00704   -28.9    2.13e-146
 4 cluster3                         -0.257      0.00543   -47.2    6.97e-298
 5 Primary_AI_ToolClaude 3.5         0.00153    0.00664     0.230  8.18e-  1
 6 Primary_AI_ToolGemini Pro        -0.00604    0.00661    -0.913  3.61e-  1
 7 Primary_AI_ToolGitHub Copilot    -0.00687    0.00656    -1.05   2.95e-  1
 8 Primary_AI_ToolPerplexity        -0.000990   0.00661    -0.150  8.81e-  1
 9 Task_Frequency_Daily              0.0000865  0.000716    0.121  9.04e-  1
10 Main_Usage_CaseCode Debugging    -0.0000691  0.00685    -0.0101 9.92e-  1
11 Main_Usage_CaseEssay Drafting     0.00735    0.00664     1.11   2.68e-  1
12 Main_Usage_CaseExam Prep          0.00147    0.00643     0.228  8.20e-  1
13 Main_Usage_CaseLiterature Review  0.00204    0.00660     0.310  7.57e-  1
14 Time_Saved_Hours_Weekly          -0.00315    0.000517   -6.10   1.35e-  9</code></pre>
</div>
</div>
<p>The model shows extremely high explanatory power (R² ≈ 0.97), driven almost entirely by baseline GPA.</p>
<ul>
<li><code>GPA_Baseline ≈ 1.01</code> → near-perfect persistence</li>
<li>AI usage variables → non-significant</li>
<li><code>Time_Saved_Hours_Weekly</code> → small negative effect</li>
</ul>
<p><strong>Cluster effects:</strong></p>
<ul>
<li>Cluster 2 “high GPA baseline”: <code>−0.20</code> GPA points (vs cluster 1 “improvers”)</li>
<li>Cluster 3 “low GPA baseline”: <code>−0.26</code> GPA points (vs cluster 1 “improvers”)</li>
</ul>
<p>Holding baseline GPA constant, <strong>cluster membership</strong> remains strongly associated with outcomes.</p>
<p>Cluster effects capture residual performance differences not explained by observed variables. However, because clusters are partially constructed from GPA-related variables, these effects should be interpreted as <strong>latent performance regimes, not causal drivers</strong>.</p>
<p><code>Time_Saved_Hours_Weekly</code> has a coefficient of -0.00315 (p &lt; 0.001). Higher reported time savings may result in slightly lower GPA, the baseline GPA and clustering being controlled for. The magnitude of the impact is small, but statistically clear. The influence might be a result of a latent **substitution effect* (students saving time may reduce effort); over-reliance; or efficiency replacing deep processing and deep learning.</p>
<hr>
</section>
</section>
</section>
<section id="sec-main-results" class="level2">
<h2 class="anchored" data-anchor-id="sec-main-results">Main results</h2>
<p>The analysis produces several consistent findings across descriptive statistics, hypothesis testing, modeling, and clustering.</p>
<p><strong>1. Strong persistence of academic performance</strong></p>
<p>Post-AI GPA is almost entirely determined by baseline GPA. Across all models, prior performance explains the overwhelming majority of variance, indicating a highly stable academic structure.</p>
<p><strong>2. No measurable effect of AI usage variables</strong></p>
<p>AI-related variables — tool, usage frequency, usage case, and time saved — do not meaningfully explain academic outcomes.</p>
<p>This result is robust across:</p>
<ul>
<li>OLS models</li>
<li>logistic models</li>
<li>correlation analysis</li>
</ul>
<p>AI usage intensity does not translate into measurable GPA differences.</p>
<p><strong>3. Negative association between time saved and performance</strong></p>
<p>Time saved is the only AI-related variable showing a statistically significant effect in the final model, with a small negative coefficient.</p>
<p>This suggests that perceived efficiency gains may not correspond to improved learning outcomes.</p>
<p><strong>4. Weak structure of subjective variables</strong></p>
<p>Career confidence and ethical concerns are only weakly connected to both GPA and AI usage variables.</p>
<p>These dimensions appear largely independent from observed academic performance.</p>
<p>Ethical concern shows only a weak association with AI usage frequency and an effect of familiarity: the more you use the AI tools, the less you are concerned with their ethical implications.</p>
<p><strong>5. Existence of latent performance profiles</strong></p>
<p>Clustering reveals three distinct profiles primarily structured by:</p>
<ul>
<li>baseline academic level</li>
<li>GPA evolution</li>
<li>Career confidence score</li>
</ul>
<p>AI usage variables do not strongly differentiate these groups.</p>
<p>When integrated into regression models, clusters remain statistically very significant, indicating the presence of unobserved heterogeneity in academic trajectories.</p>
<p><strong>6. AI as a capability-dependent amplifier</strong></p>
<p>The combined evidence suggests that AI does not function as a universal performance enhancer.</p>
<p><em>Instead:</em></p>
<p>AI appears to act as a <strong>capability-dependent amplifier</strong>, where outcomes depend on baseline skills and the ability to use the tool effectively.</p>
<ul>
<li>intermediate students benefit the most;</li>
<li>high performers show limited gains (ceiling effect);</li>
<li>lower-performing students may not benefit, or may even be negatively affected.</li>
</ul>
<hr>
</section>
<section id="sec-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="sec-interpretation">Interpretation</h2>
<p>The dataset does not support a strong relationship between AI usage and academic outcomes. The strongest statistical relationship found here is the continuity between baseline GPA and post-AI GPA.</p>
<p>This suggests that academic performance is highly stable, while AI usage, career confidence, ethical concern, and time saved are weakly connected in this dataset.</p>
<p>In addition to self-reporter measurement biases and a probability of artificial origin of the dataset, this observation makes us believe that the relationship between the AI technologies and GPA scores is probably moderated by other variables not recorded in the collected data.</p>
<p>Cluster analysis yielded the most advanced results and gives us a strong impulse to suggest that AI effectiveness depends on the interaction between baseline capability and tool usage not recorded in the dataset variables.</p>
<p>AI is not a primary driver of performance. AI acts as a capability amplifier or destabilizer, depending on the user profile. The observed clusters are emergent outcomes of this interaction.</p>
<p>The relationship between baseline academic ability and AI gains appears non-monotonic, suggesting an inverted-U type dynamic.</p>
<ul>
<li>For high-performing students, AI operates under a ceiling constraint. Gains are mechanically limited, and usage appears strategic rather than transformative.</li>
<li>Students with intermediate baseline performance exhibit the highest marginal returns. Their skill set appears sufficiently developed to leverage AI outputs critically, while still leaving substantial room for improvement.</li>
<li>For lower-performing students, AI usage may substitute rather than augment learning processes. Limited evaluative capacity can lead to inefficient or counterproductive use, resulting in negligible or even negative outcomes.</li>
</ul>
<p>The results suggest that the effectiveness of AI is mediated not by usage intensity, but by usage quality — i.e., the ability to critically interpret, adapt, and integrate AI-generated outputs.</p>
<p>Observed variables capture intensity of use, but not cognitive engagement. This likely explains the absence of strong statistical relationships.</p>
<p>Our interpretations remain hypothetical, as the dataset does not include direct measures of cognitive strategies, AI literacy, or study behaviors.</p>
<div class="callout callout-style-default callout-important callout-titled" title="AI literacy and usage quality">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>AI literacy and usage quality
</div>
</div>
<div class="callout-body-container callout-body">
<p>AI does not appear to equalize academic performance. Instead, it reinforces existing trajectories: it marginally benefits high performers, significantly supports intermediate students, and may disadvantage those lacking the skills required to use it effectively.</p>
<p>The observed pattern is consistent with a skill-biased effect of AI usage, where returns depend on the user’s ability to integrate the tool into existing cognitive processes. <strong>Matthew effect: “the rich get richer”.</strong></p>
</div>
</div>
<hr>
</section>
<section id="sec-limitations" class="level2">
<h2 class="anchored" data-anchor-id="sec-limitations">Limitations</h2>
<p>Several limitations should be considered:</p>
<ul>
<li>The dataset is observational and does not include a control group.</li>
<li>GPA differences are discretized and affected by rounding.</li>
<li>AI usage variables are self-reported rather than directly observed.</li>
<li>The dataset includes only limited socio-demographic controls.</li>
<li>Some variables appear weakly connected, suggesting limited internal structure.</li>
<li>Statistical significance does not necessarily imply practical impact.</li>
<li>The dataset may be synthetic or simplified, which limits real-world generalization.</li>
</ul>
<hr>
</section>
</section>
<section id="python-data-analysis-project" class="level1">
<h1>2. Python data analysis project</h1>
<p>Coming soon.</p>
<p>This section will present a Python-based project using pandas, numpy, and visualization libraries to explore, clean, and model a structured dataset.</p>
<hr>
</section>
<section id="sql-and-database-project" class="level1">
<h1>3. SQL and database project</h1>
<p>Coming soon.</p>
<p>This section will present a database-oriented project focused on data modeling, SQL queries, relational structuring, and possibly graph database logic.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>